#spring:
#   thymeleaf:
#     cache: false
#     encoding: utf-8
#     mode: HTML5
#     suffix: .html

#plconfiguration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutIm

mybatis:
  mapper-locations: classpath:mappers/*.xml